extends SceneTree
const Replay = preload("res://scripts/melee_replay.gd")
var failures := 0
func check(condition: bool, message: String) -> void:
	if not condition:
		failures += 1
		push_error(message)
func _initialize() -> void:
	var replay := Replay.new()
	check(not replay.begin_replay(), "empty capture")
	for index in 2700:
		replay.record(1.0 / 90.0, {"pose": Transform3D(Basis(Vector3.UP, index * 0.001), Vector3(index, 0, 0)), "events": [{"hit": index}] if index % 3 == 1 else [], "nested": {"v": Vector3(1, 2, 3)}})
	check(replay.frame_count() <= 601 and replay.frame_count() >= 599, "bounded 30 Hz ring")
	check(replay.begin_replay() and replay.duration() <= 20.001, "bounded clip")
	var count := replay.frame_count()
	replay.record(1.0, {})
	check(replay.frame_count() == count, "capture frozen during replay")
	replay.scrub(0.5)
	var pose: Transform3D = replay.sample().pose
	replay.advance(1.0)
	check(is_equal_approx(replay.cursor, 0.5), "pause remains still")
	replay.toggle_playing()
	replay.advance(0.25)
	check(is_equal_approx(replay.cursor, 0.75), "play advances")
	replay.scrub(-5.0)
	check(replay.cursor == 0.0 and not replay.playing, "scrub clamps and pauses")
	replay.scrub(0.5)
	check(replay.add_annotation("felt sticky"), "annotation")
	var path := "user://melee-replay-test.json"
	check(replay.save_file(path, {"build": "test", "integer": 4}) == OK, "export")
	var loaded := Replay.new()
	check(loaded.load_file(path) == OK, "import")
	loaded.scrub(0.5)
	check(loaded.sample().pose.is_equal_approx(pose), "transform round trip")
	check(loaded.sample().nested.v == Vector3(1, 2, 3), "nested vector round trip")
	check(loaded.annotations[0].text == "felt sticky" and loaded.annotations[0].time == 0.5, "annotation round trip")
	check(loaded.metadata.build == "test" and loaded.metadata.integer is int, "metadata and integer type round trip")
	check(loaded.sample().events.size() == 1, "events between replay ticks retained")
	var original := FileAccess.get_file_as_string(path)
	var malformed: Dictionary = JSON.parse_string(original)
	malformed.annotations = [{"time": 99999.0, "text": "outside clip"}]
	var bad_file := FileAccess.open(path, FileAccess.WRITE)
	bad_file.store_string(JSON.stringify(malformed))
	bad_file.close()
	check(loaded.load_file(path) == ERR_INVALID_DATA, "out of bounds annotation rejected")
	malformed = JSON.parse_string(original)
	malformed.frames = [{"$type": "Vector3", "value": ["wrong", 0, 0]}]
	bad_file = FileAccess.open(path, FileAccess.WRITE)
	bad_file.store_string(JSON.stringify(malformed))
	bad_file.close()
	check(loaded.load_file(path) == ERR_INVALID_DATA, "malformed vector rejected without throwing")
	var file := FileAccess.open(path, FileAccess.WRITE)
	file.store_string('{"version":999}')
	file.close()
	check(loaded.load_file(path) == ERR_INVALID_DATA, "invalid file rejected")
	check(loaded.sample().pose.is_equal_approx(pose), "invalid import preserves existing clip")
	check(loaded.load_file("user://nonexistent-melee-replay.json") != OK, "missing file rejected")
	DirAccess.remove_absolute(path)
	var linear := Replay.new()
	linear.record(1.0 / 30.0, {"pose": Transform3D.IDENTITY, "contacts": [{"position": Vector3.ZERO}]})
	linear.record(1.0 / 30.0, {"pose": Transform3D(Basis.IDENTITY, Vector3(2, 0, 0)), "contacts": [{"position": Vector3(2, 0, 0)}]})
	linear.begin_replay()
	linear.scrub(1.0 / 60.0)
	check(linear.sample().pose.origin.is_equal_approx(Vector3(1, 0, 0)), "pose interpolation")
	check(linear.sample().contacts[0].position == Vector3.ZERO, "contact records stay discrete")
	var hidden := Transform3D(Basis.IDENTITY.scaled(Vector3.ZERO), Vector3.ZERO)
	check(linear._interpolate(hidden, Transform3D.IDENTITY, 0.5) == hidden, "hidden zero-scale leaf stays discrete")
	print("MELEE_REPLAY_TEST ", "PASS" if failures == 0 else "FAIL", " failures=", failures)
	quit(1 if failures else 0)
